adding the last version of the logger class
7map/7map pull request #44
Opened 2021-05-09 03:04 UTC by kingussopp

2021-05-09 07:53 UTC, l3alr0g requested changes
I know this probably took you a long time to figure out, but the requirements for this PR to be merged are not met at all. Please take some time to read the comments I wrote, then message me on discord if you need some help understanding what you did wrong (in this order, not the other way around).

2021-05-09 07:53 UTC, l3alr0g commented on src/main/java/com/sevenmap/App.java
> +    public static Logger logger = null;
Why do you initialize your logger this way ? My guess is you should call the default constructor (or simply create one)

2021-05-09 07:53 UTC, l3alr0g commented on src/main/java/com/sevenmap/App.java
> +import java.io.File;
Unused import

2021-05-09 07:53 UTC, l3alr0g commented on src/main/java/com/sevenmap/logger.java
> +          logger.log(Level.INFO, "Info message from Throwable object", new Throwable("Throwable exception"));
I plainly don't understand what you meant to do here, why do you generate these test logs inside the main function ? Why doesn't the class have a `log(message)` method of its own ? The logger class is supposed to be an alternative to the classic `System.out.println()` call, and in this case, I don't see how anyone could use it that way.

2021-05-09 07:53 UTC, l3alr0g commented on src/test/java/com/sevenmap/ui/maths/Vector3fTest.java
> +        public void normalizeTest() {
Minor detail : please fix this indentation.

2021-05-09 10:15 UTC, kingussopp commented
For the null logger initialisation and the useless imports I was trying to figure out how to implement the logger in the main class(app.java). but when I couldn't, I just - forgot to delete those lines(among others). It seems that I didn't fully understand the purpose of the logger. Will I be replacing every system.out.print() if things went right ?

2021-05-09 10:22 UTC, l3alr0g commented
Yes, that is the point of a logger, it is meant to replace the vanilla `System.out.println()` method by allowing you to (for instance) store the logs in a file or simply not display them, something `println` can't do.

2021-05-09 10:27 UTC, kingussopp commented
So the way I see it, the logger class wouldn't need a main method, I will be just using simple methods that each will describe a certain step or error.

2021-05-09 10:32 UTC, l3alr0g commented
That's right, you got the idea. You get to decide whether these methods will be static or not (if not then the logger obviously needs to be instantiated). I've converted this PR to draft, so any changes/commits you make will be added to it : no need to create a new one.
When you're done fixing everything, mark it as ready for review, I should be notified.

2021-05-09 10:35 UTC, kingussopp commented
Ok great, thanks for the help.

2021-05-29 10:58 UTC, l3alr0g commented on src/test/java/com/sevenmap/ui/maths/Vector3fTest.java
> +        public void normalizeTest() {
still not fixed

2021-05-29 10:59 UTC, l3alr0g commented on src/main/java/com/sevenmap/App.java
> +    public static Logger logger = null;
can you please modify this ?

2021-05-29 11:00 UTC, l3alr0g requested changes
Not ready to merge

2021-05-29 13:30 UTC, l3alr0g approved these changes
Approved for merging, everything seems fine

2021-05-29 13:30 UTC, merged